Repository Doumor/metr1c, pull requests merged in 2024-05, with the labels that each got.

#19 CI workflow for testing Makefile instructions
  .github/workflows/build.yaml
  .gitignore
  Makefile
  README.md
  go.mod
  go.sum
  main.go
Labels: 🤖 ci, 🚧 wip

#29 Rac parsing #27
  go.mod
  go.sum
  main.go
  rac/rac.go
  rac/rac_test.go
Labels: 📶 enhancement

#38 Add active/hibernate session count and licenses count by soft/hasp usage
  main.go
  rac/rac.go
Labels: ✨ feature

#40 add to exported metrics total number of connections
  main.go
Labels: ✨ feature

#39 add to exported metrics total number of processes
  main.go
Labels: ✨ feature

#41 export total memory used by processes
  main.go
Labels: ✨ feature

#48 Refactor API code to remove redundancy
  api/api.go
  main.go
Labels: 🔄 refactoring

#47 Metrics goroutine #46
  main.go
  main_test.go
Labels: 🔄 refactoring

#50 API implementation
  api/api.go
  main.go
Labels: ✨ feature
