Repository Doumor/metr1c, pull requests merged in 2024-04, with the labels that each got.

#13 Fix spelling issues in README.md
  README.md
Labels: 🗒️ documentation

#9 Add install option to makefile
  .gitignore
  Makefile
  README.md
Labels: ✨ feature

#21 Check http call exit value
  main.go
Labels: 🤖 ci

#22 Use 'flag' from std for argument parsing
  main.go
Labels: 📶 enhancement, ✨ feature

#23 Translate to english. Minor naming fixes
  main.go
Labels: 🗒️ documentation
